<?php

/**
 * @file
 * This file demonstrates how to use hook functions.
*/

/**
 * Implements hook_cron().
 * https://api.drupal.org/api/drupal/core%21core.api.php/function/hook_cron/10
 */

function mymodule_cron() {
  \Drupal::messenger()->addMessage(t('Hello from mymodule_cron!'));
}

/**
 * Implements hook_form_alter().
 * https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Form!form.api.php/function/hook_form_alter/10
 */
function mymodule_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // \Drupal::messenger()->addMessage(t('Form ID: @id', ['@id' => $form_id]));
  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = t('Save this awesome article!');
  }
}